### ISSUE TITLE
Can't push to GitHub

### ISSUE THREAD

**Issue by tanatc1256** [comp426-2023-spring/e02#3]
***Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below.***

#### Description
When I tried to push after commit my changes, it won't let me.

#### Screenshots
![git error](https://user-images.githubusercontent.com/69814826/236743830-9d544321-d60d-42b6-9351-f8cd84e6de35.png)

#### File (link)
my GitHub e02 link: https://github.com/comp426-2023-spring/e02-tanatc1256

#### Steps to reproduce
have non-local work in the remote?

#### Steps to resolve
have that non-local work locally?

**Comment by jdmar3** [comment]
Do `git pull` first, like it literally says in the error message, and then push again.
